### ISSUE TITLE
Support for optional query parameters

### ISSUE THREAD

**Issue by toxygene** [tebru/retrofit-php#8]
Currently, all @Query parameters are sent to the server, regardless of if they are required or not. It would be nice to be able to specify some @Query annotations as optional so they are not sent to the server if they are null.

**Comment by natebrunette** [comment]
Is this still an issue with support for JMS serialization contexts?

**Comment by natebrunette** [comment]
I believe a temporary solution for now would be to utilize the added support for jms serialization contexts.  This should be fully implemented in v3

**Comment by natebrunette** [comment]
All null values have been excluded since it was switched to use `http_build_query` to create all query strings.  Unfortunately, they are still not optional, as they are always excluded if null.  I think that's a much rarer case, though.  A workaround would be to set the null values to empty string (or some other value the api would accept) in the user-land code.

I'm closing this for now, but feel free to open another issue if you do need the reverse behavior and the above solution is not sufficient.
